version: "3.9"

services:
  backend:
    build: "https://github.com/couchbaselabs/try-cb-python.git#7.0"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - CB_HOST
      - CB_USER
      - CB_PSWD
    command: $CB_HOST $CB_USER $CB_PSWD
    container_name: fe-try-cb-api

  frontend:
    build: .
    ports:
      - 8081:8081
    container_name: fe-try-cb-fe
    entrypoint: ["wait-for-it", "backend:8080", "--timeout=200", "--strict", "--", "npm", "run", "serve"]
    depends_on:
      backend:
        condition: service_started

  db:
    image: couchbase/server-sandbox:7.0.0
    ports:
      - "8091-8095:8091-8095"
      - "11210:11210"
    expose: # expose ports to other containers (mainly for backend)
      - "8091"
      - "8094"
    healthcheck: # checks couchbase server is up
      test: ["CMD", "curl", "--head", "http://localhost:8091/pools"]
      interval: 20s
      timeout: 20s
      retries: 2
    container_name: fe-couchbase-sandbox-7.0.0
